name: Hello GitHub Actions

on: [push]

jobs:
  workspace-job:
    runs-on: ubuntu-latest
    steps:
      - name: Create a text file in workspace
        run: echo "This file is created inside GitHub Actions workspace" > sample.txt

      - name: Display file contents
        run: cat sample.txt
